import cv2
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path


# 1. CCL & UTILITY FUNCTIONS

def find_components(binary):
    """2-pass 8-connected Component Labeling."""
    h, w = binary.shape
    labels = np.zeros((h, w), dtype=np.int32)
    parents = {}
    curr_id = 1

    for r in range(1, h - 1):
        for c in range(1, w - 1):
            if binary[r, c] > 0:
                neighbors = [
                    labels[r - 1, c - 1], labels[r - 1, c],
                    labels[r - 1, c + 1], labels[r, c - 1]
                ]
                valid = [n for n in neighbors if n > 0]

                if not valid:
                    labels[r, c] = curr_id
                    parents[curr_id] = curr_id
                    curr_id += 1
                else:
                    smallest = min(valid)
                    labels[r, c] = smallest

                    for n in valid:
                        root_a, root_b = smallest, n
                        while parents[root_a] != root_a: root_a = parents[root_a]
                        while parents[root_b] != root_b: root_b = parents[root_b]
                        if root_a != root_b:
                            parents[root_b] = root_a

    for r in range(h):
        for c in range(w):
            if labels[r, c] > 0:
                root = labels[r, c]
                while parents[root] != root:
                    root = parents[root]
                labels[r, c] = root

    return labels


def get_largest_blob(labels):
    """Keeps only the largest segmented region."""
    vals, counts = np.unique(labels[labels > 0], return_counts=True)  # counts pixels of each unique blob
    if len(counts) == 0:
        return np.zeros_like(labels, dtype=np.uint8)

    biggest_label = vals[np.argmax(counts)]  # takes biggest blob
    return (labels == biggest_label).astype(np.uint8) * 255


def get_dice_score(pred, gt_path):
    """Calculates Dice Similarity Coefficient."""
    if not os.path.exists(gt_path): return 0.0
    gt = cv2.imread(gt_path, 0)
    if gt is None: return 0.0

    p_bin = (pred > 0).astype(np.float32)
    g_bin = (gt > 0).astype(np.float32)

    overlap = np.sum(p_bin * g_bin)
    total = np.sum(p_bin) + np.sum(g_bin)

    if total == 0: return 0.0
    return (2.0 * overlap) / total


# 2. IMAGE PROCESSING PIPELINE

def enhance_image(path):
    """Applies manual contrast stretching using percentiles and masking."""
    img = cv2.imread(path)
    if img is None: return None, None, None
    # removing r and b components
    green = img[:, :, 1]
    h, w = green.shape

    # Create a circular mask to ignore the dark edges of the eye
    mask = np.zeros((h, w), dtype=np.uint8)
    cv2.circle(mask, (w // 2, h // 2), int(min(w, h) * 0.48), 255, -1)

    # Get only the pixels inside the eye
    eye_pixels = green[mask > 0]
    if len(eye_pixels) == 0: return None, None, None

    # Manual Contrast Stretching (Min-Max Normalization via Percentiles)
    # We use 2nd and 98th percentiles to avoid extreme bright/dark outliers
    p_low, p_high = np.percentile(eye_pixels, (2, 98))

    # Apply the stretching formula: (val - min) / (max - min) * 255
    stretched = np.clip((green - p_low) / (p_high - p_low + 1e-5) * 255, 0, 255).astype(np.uint8)

    # Apply standard Histogram Equalization to the stretched image for extra pop
    eq_img = cv2.equalizeHist(stretched)

    # Mask out the background noise generated by equalization
    final_gray = cv2.bitwise_and(eq_img, eq_img, mask=mask)

    # Smooth the image to blend variations
    blurred = cv2.GaussianBlur(final_gray, (11, 11), 0)

    return img, blurred, mask


def find_disc(gray, mask):
    """Finds the Optic Disc using thresholding on the stretched image."""
    pixels = gray[mask > 0]
    if len(pixels) == 0:
        return np.zeros_like(gray, dtype=np.uint8)

    # Adjusted to 90th percentile so the Disc mask grabs the full outer shape
    t = np.percentile(pixels, 90)
    binary = (gray > t).astype(np.uint8)

    labels = find_components(binary)
    disc = get_largest_blob(labels)

    # Fill holes inside the disc using inbuilt contour logic
    contours, _ = cv2.findContours(disc, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        cv2.drawContours(disc, contours, -1, 255, -1)

    return disc


def find_cup(gray, disc):
    """Finds the Optic Cup strictly inside the Optic Disc."""
    if np.sum(disc) == 0:
        return np.zeros_like(gray, dtype=np.uint8)

    pixels = gray[disc > 0]
    if len(pixels) == 0:
        return np.zeros_like(gray, dtype=np.uint8)

    # Adjusted down to 60th percentile so it actually finds the cup inside the disc
    t = np.percentile(pixels, 60)

    binary = (gray > t).astype(np.uint8)
    binary = cv2.bitwise_and(binary, binary, mask=(disc > 0).astype(np.uint8))

    labels = find_components(binary)
    cup = get_largest_blob(labels)

    return cup


# 3. I/O AND MAIN EXECUTION

def get_paths(base_dir="Drishti-GS", mode="Test"):
    """Finds all image and mask paths."""
    pairs = []
    img_dir = Path(base_dir) / mode / mode / "Images"
    gt_dir = Path(base_dir) / mode / mode / f"{mode}_GT"

    for img_path in img_dir.rglob("*.png"):
        name = img_path.stem
        cup_gt = gt_dir / name / "SoftMap" / f"{name}_cupsegSoftmap.png"
        disc_gt = gt_dir / name / "SoftMap" / f"{name}_ODsegSoftmap.png"

        if cup_gt.exists() and disc_gt.exists():
            pairs.append({
                "img": str(img_path), "cup": str(cup_gt),
                "disc": str(disc_gt), "name": name
            })
    return pairs


def run_single(item, mask_dir, plot_dir):
    """Runs the whole process for one image."""
    img, gray, mask = enhance_image(item['img'])
    if img is None: return None, None

    disc = find_disc(gray, mask)
    cup = find_cup(gray, disc)

    gt_disc = cv2.imread(item['disc'], 0)
    if gt_disc is None: gt_disc = np.zeros_like(gray)

    plt.figure(figsize=(16, 4))

    plt.subplot(1, 4, 1)
    plt.title("Original")
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

    plt.subplot(1, 4, 2)
    plt.title("Ground Truth Disc")
    plt.imshow(gt_disc, cmap='gray')

    plt.subplot(1, 4, 3)
    plt.title("My Disc")
    plt.imshow(disc, cmap='gray')

    plt.subplot(1, 4, 4)
    plt.title("My Cup")
    plt.imshow(cup, cmap='gray')

    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, f"{item['name']}_plot.png"))
    plt.close()

    cv2.imwrite(os.path.join(mask_dir, f"{item['name']}_disc.png"), disc)
    cv2.imwrite(os.path.join(mask_dir, f"{item['name']}_cup.png"), cup)

    return disc, cup


if __name__ == "__main__":
    dataset_path = "Drishti-GS"

    # This loop runs the entire program twice: once for Training, once for Test!
    for phase in ["Training", "Test"]:
        print(f"\n{'=' * 40}")
        print(f"--- Starting {phase} Phase ---")
        print(f"{'=' * 40}")

        # Creates organized folders for each phase
        out_masks = f"Results/{phase}/Masks"
        out_plots = f"Results/{phase}/Comparisons"

        for f in [out_masks, out_plots]:
            os.makedirs(f, exist_ok=True)

        # Uses the loop variable to tell the get_paths function which folder to look in
        data = get_paths(dataset_path, mode=phase)
        scores = []

        print(f"Starting run for {len(data)} images in {phase}...\n")

        for item in data:
            my_disc, my_cup = run_single(item, out_masks, out_plots)
            if my_disc is None: continue

            d_score = get_dice_score(my_disc, item['disc'])
            c_score = get_dice_score(my_cup, item['cup'])

            scores.append({"Name": item['name'], "Disc_Dice": d_score, "Cup_Dice": c_score})
            print(f"Image: {item['name']:<10} | Disc Dice: {d_score:.4f} | Cup Dice: {c_score:.4f}")

        if scores:
            df = pd.DataFrame(scores)
            print("\n" + "-" * 30)
            print(f"Avg Disc Dice ({phase}): {df['Disc_Dice'].mean():.4f}")
            print(f"Avg Cup Dice  ({phase}): {df['Cup_Dice'].mean():.4f}")
            print("-" * 30)

            # Saves the CSV with the phase name in the title
            df.to_csv(f"Results/{phase}_scores.csv", index=False)

    print("\nFinished! Check the Results folder for your Training and Test data.")

# import cv2
# import numpy as np
# import os
# import pandas as pd
# import matplotlib.pyplot as plt
# from pathlib import Path
#
#
#
# # 1. CCL & UTILITY FUNCTIONS
#
# def find_components(binary):
#     """2-pass 8-connected Component Labeling."""
#     h, w = binary.shape
#     labels = np.zeros((h, w), dtype=np.int32)
#     parents = {}
#     curr_id = 1
#
#     for r in range(1, h - 1):
#         for c in range(1, w - 1):
#             if binary[r, c] > 0:
#                 neighbors = [
#                     labels[r - 1, c - 1], labels[r - 1, c],
#                     labels[r - 1, c + 1], labels[r, c - 1]
#                 ]
#                 valid = [n for n in neighbors if n > 0]
#
#                 if not valid:
#                     labels[r, c] = curr_id
#                     parents[curr_id] = curr_id
#                     curr_id += 1
#                 else:
#                     smallest = min(valid)
#                     labels[r, c] = smallest
#
#                     for n in valid:
#                         root_a, root_b = smallest, n
#                         while parents[root_a] != root_a: root_a = parents[root_a]
#                         while parents[root_b] != root_b: root_b = parents[root_b]
#                         if root_a != root_b:
#                             parents[root_b] = root_a
#
#     for r in range(h):
#         for c in range(w):
#             if labels[r, c] > 0:
#                 root = labels[r, c]
#                 while parents[root] != root:
#                     root = parents[root]
#                 labels[r, c] = root
#
#     return labels
#
#
# def get_largest_blob(labels):
#     """Keeps only the largest segmented region."""
#     vals, counts = np.unique(labels[labels > 0], return_counts=True) #counts pixels of each unique blob
#     if len(counts) == 0:
#         return np.zeros_like(labels, dtype=np.uint8)
#
#     biggest_label = vals[np.argmax(counts)] #takes biggest blob
#     return (labels == biggest_label).astype(np.uint8) * 255
#
#
# def get_dice_score(pred, gt_path):
#     """Calculates Dice Similarity Coefficient."""
#     if not os.path.exists(gt_path): return 0.0
#     gt = cv2.imread(gt_path, 0)
#     if gt is None: return 0.0
#
#     p_bin = (pred > 0).astype(np.float32)
#     g_bin = (gt > 0).astype(np.float32)
#
#     overlap = np.sum(p_bin * g_bin)
#     total = np.sum(p_bin) + np.sum(g_bin)
#
#     if total == 0: return 0.0
#     return (2.0 * overlap) / total
#
#
# # 2. IMAGE PROCESSING PIPELINE
#
# def enhance_image(path):
#     """Applies manual contrast stretching using percentiles and masking."""
#     img = cv2.imread(path)
#     if img is None: return None, None, None
#     # removing r and b components
#     green = img[:, :, 1]
#     h, w = green.shape
#
#     # Create a circular mask to ignore the dark edges of the eye
#     mask = np.zeros((h, w), dtype=np.uint8)
#     cv2.circle(mask, (w // 2, h // 2), int(min(w, h) * 0.48), 255, -1)
#
#     # Get only the pixels inside the eye
#     eye_pixels = green[mask > 0]
#     if len(eye_pixels) == 0: return None, None, None
#
#     # Manual Contrast Stretching (Min-Max Normalization via Percentiles)
#     # We use 2nd and 98th percentiles to avoid extreme bright/dark outliers
#     p_low, p_high = np.percentile(eye_pixels, (2, 98))
#
#     # Apply the stretching formula: (val - min) / (max - min) * 255
#     stretched = np.clip((green - p_low) / (p_high - p_low + 1e-5) * 255, 0, 255).astype(np.uint8)
#
#     # Apply standard Histogram Equalization to the stretched image for extra pop
#     eq_img = cv2.equalizeHist(stretched)
#
#     # Mask out the background noise generated by equalization
#     final_gray = cv2.bitwise_and(eq_img, eq_img, mask=mask)
#
#     # Smooth the image to blend variations
#     blurred = cv2.GaussianBlur(final_gray, (11, 11), 0)
#
#     return img, blurred, mask
#
#
# def find_disc(gray, mask):
#     """Finds the Optic Disc using thresholding on the stretched image."""
#     pixels = gray[mask > 0]
#     if len(pixels) == 0:
#         return np.zeros_like(gray, dtype=np.uint8)
#
#     # Adjusted to 90th percentile so the Disc mask grabs the full outer shape
#     t = np.percentile(pixels, 90)
#     binary = (gray > t).astype(np.uint8)
#
#     labels = find_components(binary)
#     disc = get_largest_blob(labels)
#
#     # Fill holes inside the disc
#     # contours, _ = cv2.findContours(disc, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
#     # if contours:
#     #     cv2.drawContours(disc, contours, -1, 255, -1)
#
#     return disc
#
#
# def find_cup(gray, disc):
#     """Finds the Optic Cup strictly inside the Optic Disc."""
#     if np.sum(disc) == 0:
#         return np.zeros_like(gray, dtype=np.uint8)
#
#     pixels = gray[disc > 0]
#     if len(pixels) == 0:
#         return np.zeros_like(gray, dtype=np.uint8)
#
#     # Adjusted down to 60th percentile so it actually finds the cup inside the disc
#     t = np.percentile(pixels, 60)
#
#     binary = (gray > t).astype(np.uint8)
#     binary = cv2.bitwise_and(binary, binary, mask=(disc > 0).astype(np.uint8))
#
#     labels = find_components(binary)
#     cup = get_largest_blob(labels)
#
#     return cup
#
#
#
# # 3. I/O AND MAIN EXECUTION
#
# def get_paths(base_dir="Drishti-GS", mode="Test"):
#     """Finds all image and mask paths."""
#     pairs = []
#     img_dir = Path(base_dir) / mode / mode / "Images"
#     gt_dir = Path(base_dir) / mode / mode / f"{mode}_GT"
#
#     for img_path in img_dir.rglob("*.png"):
#         name = img_path.stem
#         cup_gt = gt_dir / name / "SoftMap" / f"{name}_cupsegSoftmap.png"
#         disc_gt = gt_dir / name / "SoftMap" / f"{name}_ODsegSoftmap.png"
#
#         if cup_gt.exists() and disc_gt.exists():
#             pairs.append({
#                 "img": str(img_path), "cup": str(cup_gt),
#                 "disc": str(disc_gt), "name": name
#             })
#     return pairs
#
#
# def run_single(item, mask_dir, plot_dir):
#     """Runs the whole process for one image."""
#     img, gray, mask = enhance_image(item['img'])
#     if img is None: return None, None
#
#     disc = find_disc(gray, mask)
#     cup = find_cup(gray, disc)
#
#     gt_disc = cv2.imread(item['disc'], 0)
#     if gt_disc is None: gt_disc = np.zeros_like(gray)
#
#     plt.figure(figsize=(16, 4))
#
#     plt.subplot(1, 4, 1)
#     plt.title("Original")
#     plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
#
#     plt.subplot(1, 4, 2)
#     plt.title("Ground Truth Disc")
#     plt.imshow(gt_disc, cmap='gray')
#
#     plt.subplot(1, 4, 3)
#     plt.title("My Disc")
#     plt.imshow(disc, cmap='gray')
#
#     plt.subplot(1, 4, 4)
#     plt.title("My Cup")
#     plt.imshow(cup, cmap='gray')
#
#     plt.tight_layout()
#     plt.savefig(os.path.join(plot_dir, f"{item['name']}_plot.png"))
#     plt.close()
#
#     cv2.imwrite(os.path.join(mask_dir, f"{item['name']}_disc.png"), disc)
#     cv2.imwrite(os.path.join(mask_dir, f"{item['name']}_cup.png"), cup)
#
#     return disc, cup
#
#
# if __name__ == "__main__":
#     dataset_path = "Drishti-GS"
#     out_masks = "Results/Masks"
#     out_plots = "Results/Comparisons"
#
#     for f in [out_masks, out_plots]:
#         os.makedirs(f, exist_ok=True)
#
#     data = get_paths(dataset_path, mode="Training")
#     scores = []
#
#     print(f"Starting run for {len(data)} images...\n")
#
#     for item in data:
#         my_disc, my_cup = run_single(item, out_masks, out_plots)
#         if my_disc is None: continue
#
#         d_score = get_dice_score(my_disc, item['disc'])
#         c_score = get_dice_score(my_cup, item['cup'])
#
#         scores.append({"Name": item['name'], "Disc_Dice": d_score, "Cup_Dice": c_score})
#         print(f"Image: {item['name']:<10} | Disc Dice: {d_score:.4f} | Cup Dice: {c_score:.4f}")
#
#     if scores:
#         df = pd.DataFrame(scores)
#         print("\n" + "=" * 30)
#         print(f"Avg Disc Dice: {df['Disc_Dice'].mean():.4f}")
#         print(f"Avg Cup Dice:  {df['Cup_Dice'].mean():.4f}")
#         print("=" * 30)
#         df.to_csv("Results/scores.csv", index=False)
#         print("Finished! Check the Results folder.")